onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@sentry-internal/node-native-stacktrace'
  - cpu-features
  - electron
  - electron-winstaller
  - esbuild
  - msgpackr-extract
  - oracledb
  - protobufjs
  - ssh2
